package scytale;

import java.awt.Color;
import java.awt.event.*;

public class guiClass extends javax.swing.JFrame implements ActionListener
{
    String ed;
    String overWrite;  
    String go;
    guiInput GUIi;
            
    public guiClass(guiInput GUIinput) 
    {
        GUIi = GUIinput;
        ed = "true";
        overWrite = "false";
        go = "false";
        
        GUIinput = new guiInput();
        GUIinput.setInput("");
        GUIinput.setOutput("");
        GUIinput.setEd(ed);
        GUIinput.setPassword("");
        GUIinput.setOverWrite(overWrite); 
        GUIinput.setGo(go);
        
        initComponents();
        btnEncryptDecrypt.addActionListener(this);
        btnExit.addActionListener(this);
        btnGo1.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNewFileLocation = new javax.swing.JTextField();
        txtFilePath = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnEncryptDecrypt = new javax.swing.JButton();
        txtPassword = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        lblSuccessUnsuccessful = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        lblSuccessUnsuccess = new javax.swing.JLabel();
        btnGo1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(522, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(522, 329));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 36)); // NOI18N
        jLabel1.setText("Scytale");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 10, 107, 48);

        txtNewFileLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewFileLocationActionPerformed(evt);
            }
        });
        getContentPane().add(txtNewFileLocation);
        txtNewFileLocation.setBounds(150, 115, 232, 25);
        getContentPane().add(txtFilePath);
        txtFilePath.setBounds(150, 78, 232, 25);

        jLabel2.setText("Origin File:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(75, 80, 60, 14);

        jLabel3.setText("Target File:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(72, 117, 80, 14);

        btnEncryptDecrypt.setBackground(new java.awt.Color(51, 255, 51));
        btnEncryptDecrypt.setText("Encrypt");
        btnEncryptDecrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncryptDecryptActionPerformed(evt);
            }
        });
        getContentPane().add(btnEncryptDecrypt);
        btnEncryptDecrypt.setBounds(200, 190, 100, 23);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(190, 260, 130, 25);

        jLabel5.setText("Password:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 260, 60, 20);

        btnExit.setText("Exit");
        btnExit.setToolTipText("");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(120, 430, 73, 23);
        getContentPane().add(lblSuccessUnsuccessful);
        lblSuccessUnsuccessful.setBounds(220, 390, 130, 0);

        lblMessage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblMessage);
        lblMessage.setBounds(200, 410, 300, 20);
        getContentPane().add(lblSuccessUnsuccess);
        lblSuccessUnsuccess.setBounds(210, 390, 130, 20);

        btnGo1.setText("Go");
        btnGo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGo1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnGo1);
        btnGo1.setBounds(120, 390, 73, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNewFileLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewFileLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewFileLocationActionPerformed

    private void btnEncryptDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncryptDecryptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEncryptDecryptActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnGo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGo1ActionPerformed
        //System.out.println("DEBUGDEBUGDEBUG");
    }//GEN-LAST:event_btnGo1ActionPerformed

    public void actionPerformed(ActionEvent evt)
    {
        System.out.println("checking actions");
        // Sets color of button and changes program from Encrypt to Decrypt.
        if(evt.getSource() == btnEncryptDecrypt)
        {
            if(ed.equals("true"))
            {
                btnEncryptDecrypt.setText("Decrypt");
                btnEncryptDecrypt.setBackground(Color.RED);
                ed = "false";
            }
            
            else if(ed.equals("false"))
            {
                btnEncryptDecrypt.setText("Encrypt");
                btnEncryptDecrypt.setBackground(Color.GREEN);
                ed = "true";
            }
        }
        
        //Checks that data has been entered.
        
        else if(evt.getSource() == btnExit)
        {
            if(txtFilePath.getText().equals(""))
            {
                lblSuccessUnsuccess.setVisible(true);
                lblSuccessUnsuccess.setText("Unsuccessful");
                lblSuccessUnsuccess.setForeground(Color.RED);
                lblMessage.setText("Please enter a file path to continue.");
                lblMessage.setForeground(Color.RED);
            }
            
            else if(txtNewFileLocation.getText().equals(""))
            {
                lblSuccessUnsuccess.setVisible(true);
                lblSuccessUnsuccess.setText("Unsuccessful");
                lblSuccessUnsuccess.setForeground(Color.RED);
                lblMessage.setText("Please enter a destination file path to continue.");
                lblMessage.setForeground(Color.RED);
            }
            
            else if(txtPassword.getText().equals(""))
            {
                lblSuccessUnsuccess.setVisible(true);
                lblSuccessUnsuccess.setText("Unsuccessful");
                lblSuccessUnsuccess.setForeground(Color.RED);
                lblMessage.setText("Please enter a password to continue.");
                lblMessage.setForeground(Color.RED);
            }
            
            else
            {
                GUIi.setInput(txtFilePath.getText());
                GUIi.setOutput(txtNewFileLocation.getText());
                GUIi.setPassword(txtPassword.getText());
                GUIi.setEd(ed);
                GUIi.setGo(go);
                GUIi.setOverWrite("true");
            } 
        }
        
        else if (evt.getSource() == btnGo1)
        {
            GUIi.setInput(txtFilePath.getText());
            GUIi.setOutput(txtNewFileLocation.getText());
            GUIi.setEd(ed);
            GUIi.setPassword(txtPassword.getText());
            GUIi.setOverWrite(overWrite); 
            GUIi.setGo("true");
            //System.out.println("GOOOOOOOOOOOO");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEncryptDecrypt;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblSuccessUnsuccess;
    private javax.swing.JLabel lblSuccessUnsuccessful;
    private javax.swing.JTextField txtFilePath;
    private javax.swing.JTextField txtNewFileLocation;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}

